import Head from "next/head";
import { useEffect, useState } from "react";
import { getCommits } from "../services/commits";

export default function Home() {

  const [commits, setCommits] = useState([]);

  useEffect( async () => {
    try {
      const commits = await getCommits();
      setCommits(commits);
    } catch (e) {
      // do something here
      console.error("error: ", e);
    }
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* list of commits */}
        <div>
          <ul role="list" className="divide-y divide-gray-200">
            {commits.map((commit) => (
              <li key={commit.sha} className="py-4">
                <div className="flex space-x-3">
                  <img
                    className="h-6 w-6 rounded-full"
                    src={commit.author.avatar_url}
                    alt=""
                  />
                  <div className="flex-1 space-y-1">
                    <div className="flex items-center justify-between">
                      <h3 className="text-sm font-medium">
                        {commit.author.login}
                      </h3>
                      <p className="text-sm text-gray-500">
                        {commit.commit.author.date}
                      </p>
                    </div>
                    <p className="text-sm text-gray-500">
                      Pushed: {commit.commit.message}
                    </p>
                  </div>
                </div>
              </li>
            ))}
          </ul>
        </div>
      </main>

      <footer>
        <p>footer</p>
      </footer>
    </div>
  );
}
